apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-please-deployment
  labels:
    app: news-please
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-please
  template:
    metadata:
      labels:
        app: news-please
    spec:
      containers:
        - name: news-please
          image: sharockys/news-please-ng:main
          volumeMounts:
            - name: config-volume
              mountPath: /news-please-ng-config
          command: ["python3"]
          args: ["newsplease/__main__.py", "-c", "/news-please-ng-config"]
        - name: news-please-vpn-sidecar
          image: qmcgaw/gluetun:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - secretRef:
                name: nord-secret
          env:
            - name: DNS_KEEP_NAMESERVER
              value: on
            - name: UNBLOCK
              value: cluster.local
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: 0.0.0.0/0
            - name: TZ
              value: Europe/Paris
            - name: UPDATER_PERIOD
              value: 6h
          volumeMounts:
            - name: vpn-volume
              mountPath: /gluetun
      volumes:
        - name: config-volume
          configMap:
            name: news-please-configmap
        - name: vpn-volume
          persistentVolumeClaim:
            claimName: longhorn-vpn-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vpn-pvc
  namespace: news-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-dev
  resources:
    requests:
      storage: 100Mi
