apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-please-deployment
  labels:
    app: news-please
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-please
  template:
    metadata:
      labels:
        app: news-please
    spec:
      containers:
        - name: news-please
          image: sharockys/news-please-ng:main
          volumeMounts:
            - name: config-volume
              mountPath: /news-please-ng-config
          command: ["python3"]
          args: ["newsplease/__main__.py", "-c", "/news-please-ng-config"]
        - name: news-please-vpn-sidecar
          image: qmcgaw/gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          envFrom:
            - secretRef:
                name: nord-secret
      volumes:
        - name: config-volume
          configMap:
            name: news-please-configmap
