apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
configMapGenerator:
  - name: news-please-configmap
    files:
      - sitelist.hjson
      - config.cfg
      - config_lib.cfg
secretGenerator:
  - name: vpn-secret
    literals:
      - VPN_SERVICE_PROVIDER=
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=

namespace: news-dev
